### DISCUSSION TITLE
How to Patch yaml from str into Deployment CR ?

### DISCUSSION THREAD

**Discussion by ppsite** [kube-rs/kube#1480] [Q&A] [answered]
```yaml
apiVersion: annomate.fun/v1
kind: AnnoTemplate
metadata:
  name: log-sidecar
  namespace: default
spec:
  kind: SideCar
  template: |
    - name: log-tail
      image: registry.cn-hangzhou.aliyuncs.com/log-service/logtail:latest
      command:
      - sh
      - -c
      - /usr/local/ilogtail/run_logtail.sh 10
      volumeMounts:
      - name: nginx-log
        mountPath: /var/log/nginx
```

```rust
async fn reconcile(obj: Arc<Deployment>, _ctx: Arc<()>) -> Result<Action> {
    info!("reconcile : {}", obj.name_any());
    let client = Client::try_default().await.unwrap();
    let deployments: Api<Deployment> = Api::all(client.clone());
    let anno_templates: Api<AnnoTemplate> = Api::all(client.clone());

    for anno in obj.metadata.annotations.iter() {
        for k in anno.keys() {
            if k.starts_with("annomate.fun") {
                let name = k.split("/").last().unwrap();
                info!("name: {}", name);
                let lp = ListParams::default().fields(&format!("metadata.name={}", name));
                for anno_template in anno_templates.list(&lp).await.unwrap() {
                    let yaml_objs: Value =
                        serde_yaml::from_str(&anno_template.spec.template).unwrap();
                    info!("-----> : {:?}", yaml_objs[0]["name"]);
                    // TODO 
                }
            }
        }
    }

    Ok(Action::await_change())
}
```

## Business Logic

Use Controller to watch Deployment `annotations` if any item start with `annomate.fun`,  according to this item and filter `AnnoTemplate` CRD, finally merge template into `Deployment`;

## Ask 4 Help

As code above,  I can get `anno_template.spec.template`, Now How can i patch the yaml into Deployment as Sidecar ?
