### DISCUSSION TITLE
Generating CRDs with union types

### DISCUSSION THREAD

**Discussion by Moortiii** [kube-rs/kube#1711] [Q&A]
I'm trying to generate a CRD that requires a list of items that are union members. 

I want to be able to write the following manifest:

```yaml
apiVersion: mygroup/v1
kind: SomeCRD
metadata:
  name: example
spec:
  properties:
    displayName: Some name
    actions:
      - actionConfiguration:
          existsOnTypeA: "some value"
          existsOnAllTypes: "a"
        actionType: "Action A"
      - actionConfiguration:
          existsOnTypeA: "some new value"
          existsOnAllTypes: "b"
        actionType: "Action A"
      - actionConfiguration:
          existsOnTypeB: "some other value"
          existsOnAllTypes: "c" 
        actionType: "Action B"
```

In this case, the schema for `actionConfiguration` depends on the value of `actionType` which serves as a discriminator.

Using the code below, `RunPlaybookAction`, `AddIncidentTagAction` and `ModifyPropertiesAction` becomes a top-level property for each item in `actions`.

```rust
#[derive(Serialize, Deserialize, Debug, PartialEq, Clone, JsonSchema)]
pub enum ActionAType {
    #[serde(rename = "Action A")]
    ActionA,
}

#[derive(Serialize, Deserialize, Debug, PartialEq, Clone, JsonSchema)]
pub enum ActionBType {
    #[serde(rename = "Action B")]
    ActionB,
}

#[derive(Serialize, Deserialize, Debug, PartialEq, Clone, JsonSchema)]
pub enum Action {
    #[serde(rename_all = "camelCase")]
    ActionA {
        action_type: ActionAType,
        action_configuration: ActionAProperties,
    },
    #[serde(rename_all = "camelCase")]
    ActionB {
        action_type: ActionBType,
        action_configuration: ActionBProperties,
    },
}

#[derive(Serialize, Deserialize, Debug, PartialEq, Clone, JsonSchema)]
#[serde(rename_all = "camelCase")]
struct Properties {
    actions: Vec<Action>,
    display_name: String,
}
```

Is the use case I want to achieve supported, or can someone point me in the right direction?
