### DISCUSSION TITLE
"admission" feature not available?

### DISCUSSION THREAD

**Discussion by kelko** [kube-rs/kube#514] [Q&A] [answered]
I'm trying to make an Admission controller like described in [the example](https://github.com/clux/kube-rs/blob/master/examples/admission_controller.rs).
With "simple" kube dependency I get the error, that `kube::api::admission` does not exist. Checked the `Cargo.toml` of the example directory and added the [`features = ["admission"]`](https://github.com/clux/kube-rs/blob/master/examples/Cargo.toml#L24) also to my Cargo.toml:
```toml
# ...
kube = { version = "0.52.0", features = ["admission"] }
kube-runtime = "0.52.0"
kube-derive = "0.52.0"
k8s-openapi = { version = "0.11.0", default-features = false, features = ["v1_18"] }
# ..
```

But now `cargo build` complains:
```
error: failed to select a version for `kube`.
    ... required by package `lsoperator v0.1.0 (SOMEFOLDER)`
versions that meet the requirements `=0.52.0` are: 0.52.0

the package `lsoperator` depends on `kube`, with features: `admission` but `kube` does not have these features.


failed to select a version for `kube` which could resolve this conflict
```

Installed versions (on a win 10):
```
> cargo --version
cargo 1.52.0 (69767412a 2021-04-21)

> rustc --version
rustc 1.52.1 (9bc8c42bb 2021-05-09)
```

I'm still rather new to rust, maybe I just missed something. Then a pointer in the right direction would be very much appreciated.

**Comment by clux** [comment]
Ah, sorry. I have kept the feature in `master` for a while [before releasing it](https://github.com/clux/kube-rs/blob/master/CHANGELOG.md#unreleased). I am planning on releasing it this weekend, but if you want to use it in the mean time you have to use a cargo git dependency.

**Comment by nightkr** [comment, marked as answer]
In the meantime, you can use a git dependency by replacing your kube-rs dependencies with:

```toml
kube = { git = "https://github.com/clux/kube-rs.git", features = ["admission", "derive"] }
kube-runtime = { git = "https://github.com/clux/kube-rs.git" }
```

You generally don't need a separate dependency on `kube-derive`, as long as `kube`'s `derive` feature is enabled.
