### ISSUE TITLE
Auth error with oidc login kubectl plugin

### ISSUE THREAD

**Issue by atassis** [kube-rs/kube#1046]
### Current and expected behavior

I have kubeconfig with next user field:
```yaml
users:
- name: oidc-keycloak
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: kubectl
      args:
        - oidc-login
        - get-token
        - --oidc-issuer-url=<keycloak url>
        - --oidc-client-id=kubernetes
        - --oidc-client-secret=<our secret>
      env: null
      provideClusterInfo: false
```
And receive the next error during initialization (the same code as in `examples/kubectl.rs`):
```
Error: auth error: auth exec command '"kubectl" "oidc-login" "get-token" "--oidc-issuer-url=<keycloak url>" "--oidc-client-id=kubernetes" "--oidc-client-secret=<our secret>"' failed with status exit code: 2: Output { status: ExitStatus(ExitStatus(2)), stdout: "", stderr: "error: One of the values isn't valid for an argument\n" }
```

### Additional context

Windows OS
Rust version:
```
stable-x86_64-pc-windows-msvc (default)
rustc 1.64.0 (a55dd71d5 2022-09-19)
```

### Environment

Client Version: v1.25.0
Kustomize Version: v4.5.7
Server Version: v1.22.14

### Configuration and features

```toml

kube = { version = "0.75.0", features = ["runtime", "derive"] }
k8s-openapi = { version = "0.16.0", features = ["v1_25"] }
```

### Would you like to work on fixing this bug?

maybe
