### ISSUE TITLE
Segfault on musl when running in alpine

### ISSUE THREAD

**Issue by p-alik** [kube-rs/kube#1058]
### Current and expected behavior

This code 
```
fn main() {
    tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .unwrap()
    .block_on(async {
    match kube::client::Client::try_default()
            .await {
              Ok(_) => (),
              Err(error) => eprintln!("{error:?}")
            }
            // .expect("Expected a valid KUBECONFIG environment variable.");
    });
}
```
compiles well, but the binary crashes. See attachet [backtrace.txt](https://github.com/kube-rs/kube/files/9862811/backtrace.txt)

```
20:05 $ rustc --version
rustc 1.66.0-nightly (758f19645 2022-10-24)
20:01 $ OPENSSL_DIR="/home/apastuchov/git/openssl/openssl/build" RUSTFLAGS="-C target-feature=+crt-static" cargo run --bin seg-fault --target x86_64-unknown-linux-musl
```

### Environment

```
19:58 $ kubectl version --output json
{
  "clientVersion": {
    "major": "1",
    "minor": "25",
    "gitVersion": "v1.25.2",
    "gitCommit": "5835544ca568b757a8ecae5c153f317e5736700e",
    "gitTreeState": "clean",
    "buildDate": "2022-09-21T14:33:49Z",
    "goVersion": "go1.19.1",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "kustomizeVersion": "v4.5.7",
  "serverVersion": {
    "major": "1",
    "minor": "23",
    "gitVersion": "v1.23.9",
    "gitCommit": "c1de2d70269039fe55efb98e737d9a29f9155246",
    "gitTreeState": "clean",
    "buildDate": "2022-07-13T14:19:57Z",
    "goVersion": "go1.17.11",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}
```

### Configuration and features

```toml
k8s-openapi = { version = "0.16", default-features = false, features = ["v1_25"] }
kube = { version = "0.75.0", default-features = true, features = ["derive", "runtime", "client", "rustls-tls"] }
```

### Would you like to work on fixing this bug?

maybe
