### ISSUE TITLE
Store.state() returns nothing

### ISSUE THREAD

**Issue by JPFrancoia** [kube-rs/kube#1066]
### Current and expected behavior

Hi,

I'm having some trouble with pulling the state of my custom resources through a reflector.

```rust
let ns = env::var("NAMESPACE").expect("Need NAMESPACE evar");

let fancy_cr: Api<FancyStruct> = Api::namespaced(client.clone(), &ns);
let (fancy_store, writer) = reflector::store::<FancyStruct>();
let lp = ListParams::default().timeout(20);

// I do see resources' name properly printed
for r in fancy_cr.list(&ListParams::default().timeout(20)).await? {
        println!("Found resource: {}", r.name());
}

let rf = reflector(writer, watcher(fancy_cr, lp));

# Will print: "State: []" -> This is empty
println!("State: {:?}", fancy_store.state());
```

With the snippet above, I can list my custom resources (I can print their name). However calling `state()` doesn't return anything, so I can't continuously watch the state of my resources.

Would you mind helping me figuring that out please?

### Environment

Client Version: v1.21.14
Server Version: v1.21.14-eks-6d3986b

### Configuration and features

```toml
kube = { version = "0.76.0", features=["rustls-tls", "runtime"], default-features = false}
k8s-openapi = { version = "0.16.0", features = ["v1_25"] }
```
