### ISSUE TITLE
getting "unexpected EOF during chunk size line" when showing container logs

### ISSUE THREAD

**Issue by Masber** [kube-rs/kube#1075]
### Current and expected behavior

I use a code like this to get container logs:
```
    use futures_util::{StreamExt, TryStreamExt};
...
                let mut logs = pods_api
                .log_stream(
                    &cfs_session_pod_name, 
                    &kube::api::LogParams {
                        follow: true,
                        // tail_lines: Some(1),
                        container: Some(container_name),
                        ..kube::api::LogParams::default()
                    }
                ).await?.boxed();
                
                while let Some(line) = logs.try_next().await? {
                    print!("{}", std::str::from_utf8(&line).unwrap());
                }
```

This code shows container logs however it fails after a while with the error message:

```
Error: HyperError(hyper::Error(Body, hyper::Error(Body, Custom { kind: UnexpectedEof, error: "unexpected EOF during chunk size line" })))
```

### Environment

```
Client Version: v1.22.1
Server Version: v1.21.4
```

### Configuration and features

```toml
kube = { version = "0.74.0", features = ["runtime", "derive", "native-tls", "ws"] }
k8s-openapi = { version = "0.15.0", features = ["v1_24"] }
```
