### ISSUE TITLE
`kubectl explain` can't explain fields in CRDs that contain `Option<T>`'s

### ISSUE THREAD

**Issue by Dav1dde** [kube-rs/kube#1078]
### Current and expected behavior

The following definition:

```rs
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub namespace_resource_blacklist: Option<Vec<k8s_argocd::AppProjectNamespaceResourceBlacklist>>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub namespace_resource_blacklist_additional:
        Vec<k8s_argocd::AppProjectNamespaceResourceBlacklist>,
```

Generates the CRD:
```yaml
                namespaceResourceWhitelist:
                  items:
                    properties:
                      group:
                        type: string
                      kind:
                        type: string
                    required:
                      - group
                      - kind
                    type: object
                  nullable: true
                  type: array
                namespaceResourceWhitelistAdditional:
                  items:
                    properties:
                      group:
                        type: string
                      kind:
                        type: string
                    required:
                      - group
                      - kind
                    type: object
                  type: array
```
(Note: the only difference is the `nullable: true` field)

Using `kubectl explain` we get this (descriptions etc. omitted):
```
   namespaceResourceWhitelist    <>
   namespaceResourceWhitelistAdditional    <[]Object>
```

Further inspecting the fields. 

**Without** Option:
```
└─ % k explain TenantApplication.spec.namespaceResourceWhitelistAdditional
KIND:     TenantApplication
VERSION:  yggdrasil/v1alpha1

RESOURCE: namespaceResourceWhitelistAdditional <[]Object>

DESCRIPTION:
<...snip>

FIELDS:
   group    <string> -required-

   kind    <string> -required-
```

**With** Option:
```
└─ % k explain TenantApplication.spec.namespaceResourceWhitelist
KIND:     TenantApplication
VERSION:  yggdrasil/v1alpha1

DESCRIPTION:
<...snip>
```

The type information is completely lost.

### Possible solution

Omitting the `nullable: true` field from the Schema makes it explorable via `kubectl explain`.

This is obviously a major change potentially affecting every CRD generated with `kube`.

### Additional context

The problem seems to be described [here](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#publish-validation-schema-in-openapi-v2):

> If nullable: true is set, we drop type, nullable, items and properties because OpenAPI v2 is not able to express nullable. To avoid kubectl to reject good objects, this is necessary.

The nullable behaviour described [here](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#defaulting-and-nullable), seems to indicate that this should be compatible with serde if we just never emit the `nullable` field.

### Environment

```
└─ % k version --short
Client Version: v1.25.3
Kustomize Version: v4.5.7
Server Version: v1.20.15
```

### Configuration and features

```toml
k8s-openapi = { version = "0.16", features = ["v1_25"] }
kube = "0.75"
# kube = { path = "../../../workspaces/rust/kube/kube" }
```

### Affected crates

kube-derive

### Would you like to work on fixing this bug?

yes
