### ISSUE TITLE
Generating CRD for Internally tagged enums fails

### ISSUE THREAD

**Issue by kevroletin** [kube-rs/kube#1279]
### Current and expected behavior

A structure below has [Internally tagged enum representation](https://serde.rs/enum-representations.html#internally-tagged) (which is enabled by `#[serde(tag="tag")]`)). 

```
#[serde(tag="tag")]
pub enum TaggedUnion {
    Left {
        left_value: String
    },
    Right {
        right_value: String
    }
}
```

Calling `TestObject::crd()` causes an error like:

```
Property "tag" has the schema ... enum_values: Some([String("Right")]) ... but was already defined as ... enum_values: Some([String("Left")]) ... in another subschema. The schemas for a property used in multiple subschemas must be identical'...
```

The whole error message:
```
thread 'main' panicked at 'Property "tag" has the schema Object(SchemaObject { metadata: None, instance_type: Some(Single(String)), format: None, enum_values: Some([String("Right")]), const_value: None, subschemas: None, number: None, string: None, array: None, object: None, reference: None, extensions: {} }) but was already defined as Object(SchemaObject { metadata: None, instance_type: Some(Single(String)), format: None, enum_values: Some([String("Left")]), const_value: None, subschemas: None, number: None, string: None, array: None, object: None, reference: None, extensions: {} }) in another subschema. The schemas for a property used in multiple subschemas must be identical'...
```

The test case is here https://github.com/kevroletin/kube.rs-tagged-union-test

### Additional context

This is an example of Internally tagged representation:
```
{
  "tag": "Left",
  "left_value": "123"
}
```

This is an example of Externally tagged representation. This is default and generating crd for that representations works:
```
{
  "Left": {
    "left_value": "123"
  }
}
```

It seems that the problem is related to Schema postprocesing done by kube.rs

### Environment

Client Version: v1.24.3
Kustomize Version: v4.5.4
Server Version: v1.23.17-eks-2d98532

### Configuration and features

```toml
[dependencies]
k8s-openapi = { version = "0.19.0", features = ["v1_25", "schemars"] }
kube = { version = "0.85.0", features = ["runtime", "client", "derive"] }
kube-derive = "0.85.0"
schemars = "0.8.12"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.105"
serde_yaml = "0.9.25"
```

### Affected crates

kube-derive

### Would you like to work on fixing this bug?

None
