### ISSUE TITLE
Watch Ineffectiveness and Missing Error Reporting When CRD Resource Definition Validation Mismatches Rust Code

### ISSUE THREAD

**Issue by RWDai** [kube-rs/kube#1280]
### Current Behavior:
When using  `watch` to a Custom Resource Definition (CRD) resource and the validation schema defined for that resource doesn't match the corresponding Rust code, the watch operation fails silently without generating any error messages.

### Expected Behavior:
When there is a mismatch between the CRD resource's validation schema and the Rust code , the `watch` should not only fail but also generate a clear and informative error message to indicate the mismatch. This will help users identify the issue and resolve it promptly.

### example：

crd:
``` yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: crdtest.xxx.test.group
spec:
  group: xxx.test.group
  scope: Namespaced
  names:
    plural: crdtest
    singular: crdtest
    kind: CrdTest
    shortNames:
    - cts
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - testarray
              properties:
                testarray:
                  type: array
                  items:
                    type: object
                    properties:
                      code:
                        type: string
                        minLength: 1
                      name:
                        type: string
                        minLength: 1
                    required:
                      - code
```

``` rust
#[derive(CustomResource, Deserialize, Serialize, Clone, Debug, JsonSchema)]
#[serde(rename_all = "camelCase")]
#[kube(kind = "CrdTest", group = "xxx.test.group", version = "v1", namespaced)]
pub struct K8scrdtestpec {
    pub testarray: Vec<K8scrdtestpecTestArray>,
}

#[derive(Deserialize, Serialize, Clone, Debug, JsonSchema)]
#[serde(rename_all = "camelCase")]
pub struct K8scrdtestpecTestArray {
    pub code: String,
    pub name: String,
}
```

``` yaml
apiVersion: xxx.test.group/v1
kind: CrdTest
spec:
  testarray:
  - code: test_code
     name: test_name
```

The testarray.name is can be null in rust. But CRD Definition testarray.name can be null.
When the watch takes effect, edit CrdTest as follows, and the issue will be triggered:

``` yaml
apiVersion: xxx.test.group/v1
kind: CrdTest
spec:
  testarray:
  - code: test_code
```

### Environment

``` sh
[~]# kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.0
Kustomize Version: v4.5.7
Server Version: v1.20.15
WARNING: version difference between client (1.25) and server (1.20) exceeds the supported minor version skew of +/-1
```

### Configuration and features

```toml
kube = { version = "0.80", features = ["runtime", "derive"] }
k8s-openapi = { version = "0.17", features = ["v1_21"] }
```

### Would you like to work on fixing this bug?

None
