### ISSUE TITLE
Authentication fails with custom kubectl plugin

### ISSUE THREAD

**Issue by Razz4780** [kube-rs/kube#1318]
### Current and expected behavior

`kube-rs` client fails to run custom authentication plugin. The plugin reads `KUBERNETES_EXEC_INFO` env var, which is a JSON-serialized object with two fields: `kind` and `apiVersion`. The plugin fails, because `kube-rs` client always sets `kind` to `null` when executing the command

https://github.com/kube-rs/kube/blob/c3fbe252ea30a78b4620ac14860d283e587e66ec/kube-client/src/client/auth/mod.rs#L555

`kubectl` works fine though.

Our issue: https://github.com/metalbear-co/mirrord/issues/2023

### Possible solution

Not sure yet, probably see how it's handled in [`client-go`](https://github.com/kubernetes/client-go) and do the same here.

### Additional context

```
> kubectl version                          
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.1-eks-43840fb
```

### Environment

I'll update when I get it

### Configuration and features

```toml
k8s-openapi = { version = "0.20", features = ["v1_24"] }
kube = { git = "https://github.com/Razz4780/kube", branch = "support_socks5_proxy", default-features = false, features = ["runtime", "derive", "client", "ws", "rustls-tls", "oidc", "socks5"] }
```

Used `kube` is a fork of `0.86.0` with added socks5 support, changes do not affect this bug. 

### Affected crates

kube-client

### Would you like to work on fixing this bug?

yes
