### ISSUE TITLE
Better support for `x-kubernetes` properties in schemas

### ISSUE THREAD

**Issue by clux** [kube-rs/kube#1367]
There is a slew of `x-kubernetes` [extension properties](https://github.com/kubernetes/kube-openapi/blob/master/pkg/generators/extension.go) that is usable inside CRD schemas to improve the validation and merge behaviour of structures of members.

From Kubernetes 1.25 this is being leaned into even more heavily with [x-kubernetes-validations](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#validation-rules) rules on CRD schemas:

```yaml
  openAPIV3Schema:
    type: object
    properties:
      spec:
        type: object
        x-kubernetes-validations:
          - rule: "self.minReplicas <= self.replicas"
            message: "replicas should be greater than or equal to minReplicas."
          - rule: "self.replicas <= self.maxReplicas"
            message: "replicas should be smaller than or equal to maxReplicas."
```

This type of validation makes it possible to write controllers with much richer type of native validation without having to lean on the clunkier admission controllers / admission controller frameworks to manage extraneous policy rules - and has a lot of potential use. There's a KubeConNA'23 talk called [Declarative Everything](https://www.youtube.com/watch?v=rFaWmd7Y7i0) that explores this and the direction of the feature from sig apimachinery. 

### Current Usage
Such properties can be specified via `schemars` attributes to override the schema generation for a type as per https://github.com/kube-rs/kube/blob/3a4f72414a4ad3733c2683514abff1924271759d/examples/crd_derive_schema.rs#L84-L102

This is not ideal because you then have to manage all the other schema properties for that type yourself.

#### Schemars Extensions
To properly support adding properties like this, it would be interesting to see if `schemas` which has support for a large amount of [attributes](https://graham.cool/schemars/deriving/attributes/) already, could be enhanced with a `kubernetes` attribute feature set to allow stuff like e.g.:

```rust
struct Spec {
    #[schemars(x-kubernetes-validations(
        rule = "self.minReplicas <= self.replicas",
        message = "replicas should be greater than or equal to minReplicas."
    ))]
    spec: usize,
}
```

Have asked upstream about what they think about this in https://github.com/GREsau/schemars/issues/258

#### CEL Crate?

Maybe it's better to __start__ some of this from a CEL POV because maybe we want to be able to run validations we put into CEL rules locally. In this case a crate that allows us to do something like

```rust
struct Spec {
    #[cel_validation(
        rule = "self.minReplicas <= self.replicas",
        message = "replicas should be greater than or equal to minReplicas."
    )]
    spec: usize,
}
```

in either case we probably still need something in `schemars` so that the rules are forwarded into the schema, but it means we will have our own properties (like serde/validator) that schemars can pickup on later.

And we likely would need a new crate or majorly extend the [cel-parser](https://crates.io/crates/cel-parser) / [cel-interpreter](https://crates.io/crates/cel-interpreter) crate (both of which live in [cel-rust](https://github.com/clarkmcc/cel-rust/)).
