### ISSUE TITLE
Discovery fails when ApiResourceList is not apiVersion v1

### ISSUE THREAD

**Issue by KarstenB** [kube-rs/kube#1376]
### Current and expected behavior

When KubeVirt is installed in the cluster (tested with 1.1.0) then initialisation of Discovery (`Discovery::new(client.clone()).run().await?;`) will fail. The reason is the following:
```
kube_client::client: {
 "kind": "APIResourceList",
 "apiVersion": "v1alpha3",
 "groupVersion": "subresources.kubevirt.io/v1alpha3",
 "resources": [
  {
   "name": "expand-vm-spec",
   "singularName": "",
   "namespaced": true,
   "kind": "",
   "verbs": null
  },
#... more stuff
 ]
}, Error("invalid value: string \"v1alpha3\", expected v1", line: 3, column: 25)
2023-12-18T15:27:01.325684Z ERROR reconciling object{object.ref=XXX object.reason=error policy requested retry}: vm_operator: Error while checking resources error=KupeApi(SerdeError(Error("invalid value: string \"v1alpha3\", expected v1", line: 3, column: 25)))
```
I am not quite sure if KubeVirt is doing something wrong, if there is indeed some wiggle room to do it like KubeVirt is doing it.

### Possible solution

Accept non v1 ApiVersions of ApiResourceList

### Environment

Client Version: v1.27.3
Kustomize Version: v5.0.1
Server Version: v1.28.4+k3s2

### Configuration and features

```toml
k8s-openapi = { version = "0.20.0", features = ["v1_28", "schemars"] }
kube = { version = "0.87.1", features = ["derive", "kube-client", "runtime"] }
kube-runtime = "0.87.1"
```

### Affected crates

kube-client

### Would you like to work on fixing this bug?

None
