### ISSUE TITLE
Tokio Version confict with non default features that include kube-client

### ISSUE THREAD

**Issue by Toasterson** [kube-rs/kube#1508]
### Current and expected behavior

The following dependency section in `cargo.toml` works

```toml
[dependencies]
kube = { version = "0.91.0", features = ["runtime", "derive", "ws", "gzip", "socks5", "kubelet-debug"], default-features = false }
k8s-openapi = { version = "0.22.0", features = ["latest"] }
```

### Possible solution

Update tokio to 1.38.0

### Environment

Arch linux starting a fresh crate

### Affected crates

kube-core, kube-client, kube-derive, kube-runtime

### Would you like to work on fixing this bug?

yes
