### ISSUE TITLE
inconsistency with kubectl with invalid user

### ISSUE THREAD

**Issue by aviramha** [kube-rs/kube#1593]
### Current and expected behavior

When using kube-rs over `kubectl proxy` kube-rs client doesn't work while kubectl does
```
kubectl config set-cluster testt --server=http://localhost:8001 --insecure-skip-tls-verify=true
kubectl config set-context testt --cluster=testt
kubectl config use-context testt
```
add in `~/.kube/config`

```yaml
users:
- name: testt
  user: 
    password: a
    username: a
```

and in the `testt context`:
```yaml
- context:
    cluster: testt
    user: testt
  name: testt
```

then run `kubectl get pods` (using kube-rs' kubectl example) and it will fail, while official binary works.

Found this while trying to work around https://github.com/metalbear-co/mirrord/issues/2803

### Environment

doesn't matter

### Affected crates

kube-client

### Would you like to work on fixing this bug?

No, since https://github.com/kube-rs/kube/issues/1594 is more important to me, but decided to log this issue for common knowledge.
