### ISSUE TITLE
More relaxed dependencies?

### ISSUE THREAD

**Issue by aviramha** [kube-rs/kube#1601]
I noticed that some dependencies are defined very specifically, and some have more broad requirement:
```toml
ahash = "0.8"
anyhow = "1.0.71"
assert-json-diff = "2.0.2"
async-broadcast = "0.7.0"
async-stream = "0.3.5"
async-trait = "0.1.64"
backoff = "0.4.0"
base64 = "0.22.0"
bytes = "1.1.0"
```
I think it'd make the library nicer if we'd pin only what's needed to be pinned, for example, in our case it'd reduce compilation time + size because we can reuse the dependency instead of having different versions in the build.

If that suggestion makes sense, I'd be happy to send a PR that relaxes the dependencies.
