### ISSUE TITLE
`CustomResource` derive injects empty defaults for unset fields

### ISSUE THREAD

**Issue by clux** [kube-rs/kube#1680]
### Current and expected behavior

A kube derived CRD spec using say;

```rust
#[derive(CustomResource, Deserialize, Serialize, Clone, Debug, JsonSchema)]
#[kube(kind = "Document", group = "kube.rs", version = "v1", namespaced)]
#[kube(status = "DocumentStatus")]
pub struct DocumentSpec {
    pub title: String,
    pub hide: bool,
    pub content: String,
}
```

injects the following `.spec` properties (outside the schema):
```yaml
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: documents.kube.rs
spec:
  group: kube.rs
  names:
    categories: []
    kind: Document
    plural: documents
    shortNames: []
    singular: document
  scope: Namespaced
  versions:
  - additionalPrinterColumns: []
    name: v1
    schema: BIGBLOB_NOT_RELEVANT_HERE
```

in particular
`.spec.names.categories` and `.spec.names.shortNames` and `.spec.versions[].additionalPrinterColumn` are set even without us explicitly setting the corresponding kube attributes for [printcolumn](https://docs.rs/kube/latest/kube/derive.CustomResource.html#kubeprintcolumn--rjson), [shortname](https://docs.rs/kube/latest/kube/derive.CustomResource.html#kubeshortname--sn), nor [category](https://docs.rs/kube/latest/kube/derive.CustomResource.html#kubecategory--apps).

This is a violation of the spec for CRDs;
- [shortnames and categories](https://docs.rs/k8s-openapi/latest/k8s_openapi/apiextensions_apiserver/pkg/apis/apiextensions/v1/struct.CustomResourceDefinitionNames.html) are both optional on `.spec.names`
- [print columns](https://docs.rs/k8s-openapi/latest/k8s_openapi/apiextensions_apiserver/pkg/apis/apiextensions/v1/struct.CustomResourceDefinitionVersion.html) is optional on `.spec.versions[]`

### Possible solution

Only emit these vectors when they are non-empty. If there are no values in our internal code we have never called any of the attributes and so they should be treated as unset rather than explicit empty.

### Additional context

See https://github.com/kube-rs/kube/discussions/1678

### Environment

irrelevant

### Affected crates

kube-derive

### Would you like to work on fixing this bug?

maybe
