### ISSUE TITLE
Cannot use `#[validate(...)]` in conjunction with `#[derive(CELSchema)]`

### ISSUE THREAD

**Issue by aharbis** [kube-rs/kube#1745]
### Current and expected behavior

Using `#[derive(JsonSchema)]` for a custom resource, we are able to define schema-based validation using the `#[validate(...)]` attribute, for example:

```rust
#[derive(Deserialize, Serialize, Clone, Debug, JsonSchema)]
#[serde(rename_all = "camelCase")]
pub struct MySpec {
    #[validate(length(min = 1))]
    pub my_list: Vec<String>,
}
```

which would yield `minItems: 1` in the CRD schema for the field, for example:

```yaml
myList:
  items:
    type: string
  minItems: 1
  type: array
```

However, if we switch to using `#[derive(CELSchema)]` for other validation capabilities, the `#[validate(...)]` attribute breaks:

```rust
#[derive(Deserialize, Serialize, Clone, Debug, CELSchema)] // replaced JsonSchema with CELSchema
#[serde(rename_all = "camelCase")]
pub struct MySpec {
    #[validate(length(min = 1))] // this breaks
    pub my_list: Vec<String>,
}
```

error:

```
error: cannot find attribute `validate` in this scope
   --> src/apis/example.rs:116:7
    |
116 |     #[validate(length(min = 1))]
    |       ^^^^^^^^
```

### Possible solution

Can the `validate` attribute be exposed in the `CELSchema` scope so that we don't lose this validation ability? Since `validate` gives us schema-based validation it's "free" relative to CEL which has [runtime cost](https://kubernetes.io/docs/reference/using-api/cel/#resource-constraints).

### Environment

OpenShift 4.18

### Configuration and features

```toml
k8s-openapi = { version = "0.24", features = ["latest", "schemars"] }
kube = { version = "0.99", features = ["runtime", "derive", "client"] }
```

### Would you like to work on fixing this bug?

maybe
