### ISSUE TITLE
Conflict with schemars `preserve_order` feature

### ISSUE THREAD

**Issue by HoKim98** [kube-rs/kube#1757]
### Current and expected behavior

When I enable `preserve_order` feature on schemars, the `kube-core` build has failed.

```rust
error[E0599]: no method named `append` found for struct `indexmap::map::IndexMap` in the current scope
   --> kube-core/src/cel.rs:423:38
    |
423 |             schema_object.extensions.append(&mut strategy.keys()?);
    |                                      ^^^^^^ method not found in `IndexMap<String, Value>`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `kube-core` (lib) due to 1 previous error
```

```rust
// kube-core/src/cel.rs
#[cfg(feature = "schema")]
#[cfg_attr(docsrs, doc(cfg(feature = "schema")))]
pub fn merge_strategy(s: &mut Schema, strategy: MergeStrategy) -> Result<(), serde_json::Error> {
    match s {
        Schema::Bool(_) => (),
        Schema::Object(schema_object) => {
            schema_object.extensions.append(&mut strategy.keys()?);
        }
    };

    Ok(())
}
```

### Possible solution

```rust
#[cfg(feature = "schema")]
#[cfg_attr(docsrs, doc(cfg(feature = "schema")))]
pub fn merge_strategy(s: &mut Schema, strategy: MergeStrategy) -> Result<(), serde_json::Error> {
    match s {
        Schema::Bool(_) => (),
        Schema::Object(schema_object) => {
            // Just flatten
            for (key, value) in strategy.keys()? {
                schema_object.extensions.insert(key, value);
            }
        }
    };

    Ok(())
}
```

### Environment

N/A

### Configuration and features

```toml
k8s-openapi = { version = "=0.25", features = [
    "v1_32",
] }
kube = { git = "https://github.com/kube-rs/kube.git" branch = "main" }
schemars = { version = "=0.8", features = ["preserve_order"] }
```

### Affected crates

kube-core

### Would you like to work on fixing this bug?

yes
