### ISSUE TITLE
Controller continue to reconcile when object is deleted

### ISSUE THREAD

**Issue by dmolokanov** [kube-rs/kube#712]
### Current and expected behavior

I use `Controller` to make an k8s operator. Inside my `reconcile` function it creates (via just PATCH) a number of resources (StatefulSets, Services, Deployments).  I make all my resources to have OwnerReference to the CRD. Reconcile happens every 60s.

Sometimes when I delete CRD right before reset/refresh of the watcher happens I have my controller to stuck in reconcile loop for about 2.5 min. It receives old CRD object (from cache?) despite the fact it was deleted from k8s resources.  During this time there are concurrent 2 processes happen: 
1. k8s tries to cleanup objects because of deleted CRD+owner reference
2. my operator patches missing resources because it things CRD is in place.

Expected behavior:
Controller should notice CRD object deleted and not call reconcile function.

As a side note I have questions:
1. Is it okay to rely only on PATCH operations inside reconcile function?
2. I don't see any option for Controller to receive `Deleted(CRD)` event in the separate callback/inside reconcile function. Can I rely on `ObjectNotFound` error?

### Environment

Client Version: v1.22.2
Server Version: v1.20.9

### Configuration and features

```toml
k8s-openapi = { version = "0.12.0", features = ["v1_20"], default-features = false }
kube = { version = "0.58.1", features = ["derive"] }
kube-derive = "0.61.0"
kube-runtime = "0.58.1"
```
